"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 20:33:53.715511
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_token', sa.String(length=32), nullable=False),
    sa.Column('edit_token_hash', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_feeds')),
    sa.UniqueConstraint('public_token', name=op.f('uq_calendar_feeds_public_token'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nationality_code', sa.String(length=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('slug', name=op.f('uq_drivers_slug'))
    )
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('slug', name=op.f('uq_series_slug'))
    )
    op.create_table('source_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index('ix_source_runs_source_id_started_at', 'source_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('calendar_feed_series',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['calendar_feeds.id'], name=op.f('fk_calendar_feed_series_feed_id_calendar_feeds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_calendar_feed_series_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'series_id', name=op.f('pk_calendar_feed_series'))
    )
    op.create_table('calendar_feed_session_types',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['calendar_feeds.id'], name=op.f('fk_calendar_feed_session_types_feed_id_calendar_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'session_type', name=op.f('pk_calendar_feed_session_types'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_seasons_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('series_id', 'year', name=op.f('uq_seasons_series_id'))
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_teams_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('series_id', 'slug', name=op.f('uq_teams_series_id'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('circuit_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_events_season_id_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('season_id', 'external_id', name='uq_events_season_external_id'),
    sa.UniqueConstraint('season_id', 'slug', name='uq_events_season_slug')
    )
    op.create_index('ix_events_start_date', 'events', ['start_date'], unique=False)
    op.create_table('team_drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('race_number', sa.String(length=8), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_team_drivers_driver_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_team_drivers_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_drivers_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_drivers')),
    sa.UniqueConstraint('team_id', 'driver_id', 'season_id', name=op.f('uq_team_drivers_team_id'))
    )
    op.create_index('ix_team_drivers_season_id_team_id', 'team_drivers', ['season_id', 'team_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('class_name', sa.String(length=60), nullable=True),
    sa.Column('race_number', sa.String(length=8), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('fallback_logo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_vehicles_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_vehicles_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index('ix_vehicles_team_id_season_id', 'vehicles', ['team_id', 'season_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sessions_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('event_id', 'external_id', name=op.f('uq_sessions_event_id'))
    )
    op.create_index('ix_sessions_event_id_start_at', 'sessions', ['event_id', 'start_at'], unique=False)
    op.create_index('ix_sessions_start_at', 'sessions', ['start_at'], unique=False)
    op.create_index('ix_sessions_type_start_at', 'sessions', ['session_type', 'start_at'], unique=False)
    op.create_table('session_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_changes_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_changes'))
    )
    op.create_index('ix_session_changes_detected_at', 'session_changes', ['detected_at'], unique=False)
    op.create_index('ix_session_changes_session_id_detected_at', 'session_changes', ['session_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_changes_session_id_detected_at', table_name='session_changes')
    op.drop_index('ix_session_changes_detected_at', table_name='session_changes')
    op.drop_table('session_changes')
    op.drop_index('ix_sessions_type_start_at', table_name='sessions')
    op.drop_index('ix_sessions_start_at', table_name='sessions')
    op.drop_index('ix_sessions_event_id_start_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_vehicles_team_id_season_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_team_drivers_season_id_team_id', table_name='team_drivers')
    op.drop_table('team_drivers')
    op.drop_index('ix_events_start_date', table_name='events')
    op.drop_table('events')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('calendar_feed_session_types')
    op.drop_table('calendar_feed_series')
    op.drop_index('ix_source_runs_source_id_started_at', table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_table('series')
    op.drop_table('drivers')
    op.drop_table('calendar_feeds')
    # ### end Alembic commands ###
